name: Build and deploy
on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      image: ghcr.io/${{ github.repository }}:${{ github.sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
          docker build -t ${{ env.image }} .
          docker push ${{ env.image }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          VAR: image=${{ env.image }}
          RESOURCE: .nais/config.yml
