---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: navno-prototype
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{ image }}
  port: 3123
  liveness:
    path: /prototype/internal/isAlive
    initialDelay: 5
  readiness:
    path: /prototype/internal/isReady
    initialDelay: 5
  ingresses:
    - https://www.nav.no/prototype
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
    min: 1
    max: 1
