name: Build and deploy
on:
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: personbruker
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          VAR: image=${{ steps.docker-build-push.outputs.image }}
          RESOURCE: .nais/config.yml
